from .province_form import ProvinceForm
from .commune_form import CommuneForm
from .zone_form import ZoneForm
from .specialite_form import SpecialiteForm
from .user_form import UserForm
from .cabinet_form import CabinetForm
from .medecin_form import MedecinForm
from .receptioniste_form import ReceptionisteForm
from  .horaire_form import HoraireForm
from .userReceform import ReceptionistSignUpForm
from .creneauJournalier_form import CreneauJournalierForm