# Generated by Django 4.2.4 on 2024-02-03 07:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', phone_field.models.PhoneField(max_length=31, verbose_name='Numéro de Téléphone')),
                ('role', models.CharField(choices=[('administrateur', 'Administrateur'), ('medecin', 'Médecin'), ('receptioniste', 'Receptioniste'), ('aucun', 'Aucun')], max_length=20, verbose_name='RôLE')),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, verbose_name='GENRE')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresse_complete', models.CharField(max_length=30, unique=True, verbose_name='Adrèsse Complète')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
                ('description', models.TextField(max_length=600, unique=True, verbose_name='Déscription')),
            ],
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='CreneauJournalier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut', models.TimeField(verbose_name='Début')),
                ('fin', models.TimeField(verbose_name='Fin')),
                ('pris', models.BooleanField(default=False, verbose_name='Pris')),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True, verbose_name='Nom')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Rendez_Vous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('genre', models.CharField(blank=True, choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=20, null=True)),
                ('motif', models.CharField(max_length=200)),
                ('creneauJournalier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.creneaujournalier')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Receptioniste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cabinet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=20, verbose_name='Prénom')),
                ('genre', models.CharField(choices=[('masculin', 'Masculin'), ('feminin', 'Féminin')], max_length=10, verbose_name='GENRE')),
                ('telephone', phone_field.models.PhoneField(blank=True, max_length=31, verbose_name='Téléphone du Patient')),
                ('email', models.EmailField(max_length=20, verbose_name='Email')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_images', verbose_name='Photo de profil')),
                ('specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.specialite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=30, verbose_name='Date')),
                ('heure_debut', models.TimeField(max_length=20, verbose_name='Heure_Début')),
                ('heure_fin', models.TimeField(max_length=20, verbose_name='Heure_Fin')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cabinet')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.PositiveIntegerField(verbose_name='Montant')),
                ('date_paiement', models.DateField(max_length=20, verbose_name='Date')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.rendez_vous')),
            ],
        ),
        migrations.AddField(
            model_name='creneaujournalier',
            name='horaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.horaire'),
        ),
        migrations.AddField(
            model_name='commune',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.province'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.medecin'),
        ),
        migrations.AddField(
            model_name='cabinet',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.zone'),
        ),
        migrations.AddConstraint(
            model_name='receptioniste',
            constraint=models.UniqueConstraint(fields=('user', 'cabinet'), name='unique_receptioniste'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('nom', 'prenom', 'telephone'), name='unique_patient'),
        ),
        migrations.AddConstraint(
            model_name='medecin',
            constraint=models.UniqueConstraint(fields=('user', 'specialite'), name='unique_medecin'),
        ),
    ]
