from .home import *
from .provinces import *
from .communes import *
from .zones import *
from .specialites import *
from .users import *
from .cabinets import *
from .medecins import *
from .receptionistes import *
from .horaires import *
from .public import *
from .CreneauJournalier import *
